[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.zksync]
compile = true          # Enables zkSync-compatible compilation.
fallback_oz = true      # Uses a fallback for OpenZeppelin compatibility (needed for some OZ contracts).
mode = '3'              # Enables zkSync Era compiler version 3, which is currently recommended.

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/", "foundry-devops/=lib/foundry-devops/src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
